### ISSUE TITLE
facilitate developing on non-Linux systems (OSX)

### ISSUE THREAD

**Issue by tbg** [backtrace-labs/go-bcd#1]
Can't build on OSX since the following linux-only syscalls are used:

```
# github.com/backtrace-labs/go-bcd
../../backtrace-labs/go-bcd/bcd.go:355: undefined: unix.Gettid
../../backtrace-labs/go-bcd/bcd.go:470: undefined: unix.PR_SET_PTRACER_ANY
../../backtrace-labs/go-bcd/bcd.go:471: undefined: unix.Prctl
../../backtrace-labs/go-bcd/bcd.go:471: undefined: unix.PR_SET_PTRACER
```

This could be hidden behind a build tag at the importing projects, but to facilitate development, perhaps a `!linux` build tag here with an implementation for which everything is a no-op could be given (I'm assuming that anything non-linux isn't currently supported).
In either case, documentation should address this issue (a lot of dev boxes run OSX).

**Comment by davidjoseph** [comment]
Hey @tschottdorf -- let me know if there are still issues. The latest commit uses your suggestions (build tags + updated documentation). We could provide a stubbed out BTTracer (the default tracer) implementation for non-Linux/FreeBSD systems as well, but I'd think people will want to implement their own tracers for them.

(Note: Now that the repository is public, use https://godoc.org/github.com/backtrace-labs/go-bcd for up-to-date documentation -- I'll modify the README soon.)
