### ISSUE TITLE
Facilitate developing on 32-bit ARM

### ISSUE THREAD

**Issue by nvb** [backtrace-labs/go-bcd#2]
I've run into an issue compiling go-bcd on ARM because of the issue described in https://github.com/golang/go/issues/16682. For an unknown reason, the system error number for `PR_SET_PTRACEER_ANY` is missing for the `+build arm,linux` variation of the `sys/unix` package. This causes compilation of [bcd_sys_linux.go](https://github.com/backtrace-labs/go-bcd/blob/master/bcd_sys_linux.go) to fail.

I've been working around this by changing the conditional compilation tag at the top of [bcd_sys_unsupported.go](https://github.com/backtrace-labs/go-bcd/blob/master/bcd_sys_unsupported.go) from

```
// +build !linux
```

to 

```
// +build !linux arm
```

And adding the following line to the top of [bcd_sys_linux.go](https://github.com/backtrace-labs/go-bcd/blob/master/bcd_sys_linux.go)

```
// +build !arm
```

Would you be open to a change to mark 32-bit ARM as unsupported but allow development on the system, at least until the referenced issue is resolved?

**Comment by sbahra** [comment]
Thanks for the detailed bug report @nvanbenschoten. Yes, open to it. Would it be possible for you to create a PR, and we can just merge that down?
